### ISSUE TITLE
Crash to desktop on Manjaro Linux

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [kianzarrin/AdvancedRoads#7] opened 2021-11-23 22:39 UTC
https://user-images.githubusercontent.com/14184826/143139448-bdd5e522-3d0d-4dc7-ba19-bd254e2569e8.mp4

It doesn't happen with just Harmony and TM:PE enabled.

Also happens when loading maps, not just creating new ones.

C:S is running natively; not on Proton.

**Comment by soulshadow** [comment] 2021-12-27 02:40
It's hard to determine the cause of a problem from just a video.  But based on the Loading Screen Mod messages seen in this video I'd say this LOOKS exactly like the crashes I've experienced on my linux box and discussed on the Steam Workshop page for AR.

**Comment by kianzarrin** [comment] 2021-12-27 20:12
the crash is caused by quay road patch. latest version of harmony will fix that. I will turn off that patch for now until new harmony is released.

**Comment by kianzarrin** [comment] 2021-12-28 01:31
fixed in V3.2.16

**Comment by kianzarrin** [comment] 2021-12-28 01:31
you need to wait for new harmony to use quay roads properly.

**Closed as completed** 2021-12-28 01:32 UTC
